spring:
  application:
    name: payments-service

  # Configuración de MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/payments
      uuid-representation: standard

  # Configuración de Kafka (Resiliencia y Rendimiento)
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        enable.idempotence: true # Evita duplicados en reintentos
        compression.type: zstd   # Máxima eficiencia en 2025
    consumer:
      bootstrap-servers: localhost:9092
      group-id: payments-group
      auto-offset-reset: earliest
      # Usamos String para que no falle al recibir el mensaje
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        # Esto envuelve el deserializador para que, si falla, no entre en bucle
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: "*"

# Configuración de Resiliencia (Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      paymentsService: # Solo gestiona el CB (lógica de negocio)
        registerHealthIndicator: true
      mongodbAdapter: # Gestiona el CB y el Retry (infraestructura)
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      # paymentsService: Eliminas la instancia de Retry para el servicio principal
      mongodbAdapter: # Mantienes el Retry para la base de datos
        maxAttempts: 3
        waitDuration: 500ms

# OpenAPI / Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    circuitbreakers:
      enabled: true
    retries:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,circuitbreakers,circuitbreakerevents"